/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const App: typeof import('../App')['App']
  const COLS_PER_ROW: typeof import('../constants')['COLS_PER_ROW']
  const Controller: typeof import('react-hook-form')['Controller']
  const DEFAULT_ENDPOINT_URL: typeof import('../constants')['DEFAULT_ENDPOINT_URL']
  const DEFAULT_TCP_CHECK_URL: typeof import('../constants')['DEFAULT_TCP_CHECK_URL']
  const DEFAULT_UDP_CHECK_DNS: typeof import('../constants')['DEFAULT_UDP_CHECK_DNS']
  const Fragment: typeof import('react')['Fragment']
  const GET_LOG_LEVEL_STEPS: typeof import('../constants')['GET_LOG_LEVEL_STEPS']
  const Home: typeof import('../Home')['Home']
  const QUERY_KEY_CONFIG: typeof import('../constants')['QUERY_KEY_CONFIG']
  const QUERY_KEY_GROUP: typeof import('../constants')['QUERY_KEY_GROUP']
  const QUERY_KEY_HEALTH_CHECK: typeof import('../constants')['QUERY_KEY_HEALTH_CHECK']
  const QUERY_KEY_INTERFACES: typeof import('../constants')['QUERY_KEY_INTERFACES']
  const QUERY_KEY_NODE: typeof import('../constants')['QUERY_KEY_NODE']
  const QUERY_KEY_RUNNING: typeof import('../constants')['QUERY_KEY_RUNNING']
  const QUERY_KEY_SUBSCRIPTION: typeof import('../constants')['QUERY_KEY_SUBSCRIPTION']
  const appStateAtom: typeof import('../store/index')['appStateAtom']
  const createRef: typeof import('react')['createRef']
  const endpointURLAtom: typeof import('../store/index')['endpointURLAtom']
  const forwardRef: typeof import('react')['forwardRef']
  const gqlClient: typeof import('../api')['gqlClient']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const queryClient: typeof import('../api')['queryClient']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useForm: typeof import('react-hook-form')['useForm']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useStore: typeof import('@nanostores/react')['useStore']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
  const useTranslation: typeof import('react-i18next')['useTranslation']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ForwardedRef } from 'react'
  // @ts-ignore
  export type { UseFormReturn } from 'react-hook-form'
}
