root: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
env:
  node: true
plugins:
  - "@typescript-eslint"
  - react
  - import
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:import/recommended
settings:
  import/resolver:
    typescript:
      project:
        - "apps/*/tsconfig.json"
        - "packages/*/tsconfig.json"
    node: true
rules:
  import/newline-after-import: error
  import/no-default-export: error
  import/order:
    - error
    - newlines-between: always
      groups:
        - builtin
        - type
        - external
        - internal
        - sibling
        - index
        - parent
