packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^7.4.3
  '@commitlint/cli': ^20.4.1
  '@commitlint/config-conventional': ^20.4.1
  '@emotion/react': ^11.14.0
  '@eslint-react/eslint-plugin': ^2.12.4
  '@fontsource/fira-sans': ^5.2.7
  '@fontsource/source-code-pro': ^5.2.7
  '@graphiql/toolkit': ^0.11.3
  '@graphql-codegen/cli': 6.1.1
  '@graphql-codegen/client-preset': 5.2.2
  '@graphql-codegen/introspection': 5.0.0
  '@graphql-typed-document-node/core': ^3.2.0
  '@hello-pangea/dnd': ^18.0.1
  '@hookform/resolvers': ^5.2.2
  '@monaco-editor/react': next
  '@nanostores/persistent': ^1.3.3
  '@nanostores/react': ^1.0.0
  '@radix-ui/react-accordion': ^1.2.12
  '@radix-ui/react-alert-dialog': ^1.1.15
  '@radix-ui/react-aspect-ratio': ^1.1.8
  '@radix-ui/react-avatar': ^1.1.11
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-context-menu': ^2.2.16
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-hover-card': ^1.1.15
  '@radix-ui/react-label': ^2.1.8
  '@radix-ui/react-menubar': ^1.1.16
  '@radix-ui/react-navigation-menu': ^1.2.14
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.8
  '@radix-ui/react-radio-group': ^1.3.8
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-separator': ^1.1.8
  '@radix-ui/react-slider': ^1.3.6
  '@radix-ui/react-slot': ^1.2.4
  '@radix-ui/react-switch': ^1.2.6
  '@radix-ui/react-tabs': ^1.1.13
  '@radix-ui/react-toast': ^1.2.15
  '@radix-ui/react-toggle': ^1.1.10
  '@radix-ui/react-toggle-group': ^1.1.11
  '@radix-ui/react-tooltip': ^1.2.8
  '@shikijs/monaco': ^3.22.0
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/eslint-plugin-query': ^5.91.4
  '@tanstack/react-query': ^5.90.21
  '@tanstack/react-query-devtools': ^5.91.3
  '@types/node': ^25.2.3
  '@types/react': ^19.2.14
  '@types/react-copy-to-clipboard': ^5.0.7
  '@types/react-dom': ^19.2.3
  '@types/urijs': ^1.19.26
  '@types/vscode': ^1.109.0
  '@vitejs/plugin-react': ^5.1.4
  '@vitest/ui': ^4.0.18
  '@vscode/vsce': ^3.7.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  date-fns: ^4.1.0
  dayjs: ^1.11.19
  embla-carousel-react: 8.6.0
  eslint: ^10.0.0
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.5.0
  execa: ^9.6.1
  framer-motion: ^12.34.0
  globals: ^17.3.0
  graphiql: ^5.2.2
  graphql: ^16.12.0
  graphql-request: ^7.4.0
  husky: ^9.1.7
  i18next: ^25.8.7
  i18next-browser-languagedetector: ^8.2.1
  immer: ^11.1.4
  input-otp: ^1.4.2
  js-base64: ^3.7.8
  lint-staged: ^16.2.7
  lucide-react: ^0.564.0
  monaco-editor: ^0.55.1
  nanostores: ^1.1.0
  next-themes: ^0.4.6
  playwright: ^1.58.2
  prettier: ^3.8.1
  qrcode.react: ^4.2.0
  react: ^19.2.4
  react-copy-to-clipboard: ^5.1.0
  react-day-picker: ^9.13.2
  react-dom: ^19.2.4
  react-hook-form: ^7.71.1
  react-i18next: ^16.5.4
  react-resizable-panels: ^4.6.3
  react-router: ^7.13.0
  react-router-dom: ^7.13.0
  recharts: 3.7.0
  shiki: ^3.22.0
  simple-git: ^3.30.0
  sonner: ^2.0.7
  sort-package-json: ^3.6.1
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tsdown: ^0.20.3
  tsx: ^4.21.0
  turbo: ^2.8.8
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  urijs: ^1.19.11
  vaul: ^1.1.2
  vite: ^7.3.1
  vite-plugin-environment: ^1.1.3
  vitest: ^4.0.18
  vscode-languageclient: ^9.0.1
  vscode-languageserver: ^9.0.1
  vscode-languageserver-textdocument: ^1.0.12
  zod: ^4.3.6

catalogMode: prefer

cleanupUnusedCatalogs: true

neverBuiltDependencies: []

overrides:
  vite: ^7.3.1
  lodash: ^4.17.23
  qs: ^6.14.1
  jws: ^3.2.3
  undici: ^7.18.2
  '@isaacs/brace-expansion': ^5.0.1
