neverBuiltDependencies: []

overrides:
  vite: 'npm:rolldown-vite@latest'

catalog:
  '@antfu/eslint-config': ^6.2.0
  '@commitlint/cli': ^20.1.0
  '@commitlint/config-conventional': ^20.0.0
  '@dnd-kit/core': ^6.3.1
  '@dnd-kit/modifiers': ^9.0.0
  '@dnd-kit/sortable': ^10.0.0
  '@dnd-kit/utilities': ^3.2.2
  '@emotion/react': ^11.14.0
  '@eslint-react/eslint-plugin': ^2.3.10
  '@faker-js/faker': ^10.1.0
  '@fontsource/fira-sans': ^5.2.7
  '@fontsource/source-code-pro': ^5.2.7
  '@graphiql/toolkit': ^0.11.3
  '@graphql-codegen/cli': 6.1.0
  '@graphql-codegen/client-preset': 5.2.1
  '@graphql-codegen/introspection': 5.0.0
  '@graphql-typed-document-node/core': ^3.2.0
  '@hookform/resolvers': ^5.2.2
  '@monaco-editor/react': next
  '@nanostores/persistent': ^1.2.0
  '@nanostores/react': ^1.0.0
  '@radix-ui/react-accordion': ^1.2.12
  '@radix-ui/react-alert-dialog': ^1.1.15
  '@radix-ui/react-aspect-ratio': ^1.1.8
  '@radix-ui/react-avatar': ^1.1.11
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-context-menu': ^2.2.16
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-hover-card': ^1.1.15
  '@radix-ui/react-label': ^2.1.8
  '@radix-ui/react-menubar': ^1.1.16
  '@radix-ui/react-navigation-menu': ^1.2.14
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.8
  '@radix-ui/react-radio-group': ^1.3.8
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-separator': ^1.1.8
  '@radix-ui/react-slider': ^1.3.6
  '@radix-ui/react-slot': ^1.2.4
  '@radix-ui/react-switch': ^1.2.6
  '@radix-ui/react-tabs': ^1.1.13
  '@radix-ui/react-toast': ^1.2.15
  '@radix-ui/react-toggle': ^1.1.10
  '@radix-ui/react-toggle-group': ^1.1.11
  '@radix-ui/react-tooltip': ^1.2.8
  '@shikijs/monaco': ^3.17.1
  '@tailwindcss/vite': ^4.1.17
  '@tanstack/eslint-plugin-query': ^5.91.2
  '@tanstack/react-query': ^5.90.11
  '@tanstack/react-query-devtools': ^5.91.1
  '@tiptap/extension-link': ^3.11.1
  '@tiptap/react': ^3.11.1
  '@tiptap/starter-kit': ^3.11.1
  '@types/node': ^24.10.1
  '@types/react': ^19.2.7
  '@types/react-copy-to-clipboard': ^5.0.7
  '@types/react-dom': ^19.2.3
  '@types/urijs': ^1.19.26
  '@vitejs/plugin-react': ^5.1.1
  '@vitest/ui': ^4.0.14
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  date-fns: ^4.1.0
  dayjs: ^1.11.19
  embla-carousel-react: 8.6.0
  eslint: ^9.39.1
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  execa: ^9.6.1
  framer-motion: ^12.23.24
  globals: ^16.5.0
  graphiql: ^5.2.2
  graphql: ^16.12.0
  graphql-request: ^7.3.5
  husky: ^9.1.7
  i18next: ^25.6.3
  i18next-browser-languagedetector: ^8.2.0
  immer: ^11.0.1
  input-otp: ^1.4.2
  js-base64: ^3.7.8
  lint-staged: ^16.2.7
  lucide-react: ^0.555.0
  monaco-editor: ^0.55.1
  nanostores: ^1.1.0
  next-themes: ^0.4.6
  playwright: ^1.49.1
  prettier: ^3.7.3
  qrcode.react: ^4.2.0
  react: ^19.2.0
  react-copy-to-clipboard: ^5.1.0
  react-day-picker: ^9.11.3
  react-dom: ^19.2.0
  react-hook-form: ^7.67.0
  react-i18next: ^16.3.5
  react-resizable-panels: ^3.0.6
  react-router: ^7.9.6
  react-router-dom: ^7.9.6
  recharts: 3.5.1
  shiki: ^3.17.1
  simple-git: ^3.30.0
  sonner: ^2.0.7
  sort-package-json: ^3.5.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.17
  tsx: ^4.21.0
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  urijs: ^1.19.11
  vaul: ^1.1.2
  vite: ^7.2.4
  vite-plugin-environment: ^1.1.3
  vitest: ^4.0.14
  zod: ^4.1.13
