name: Synchronize upstream

on:
  workflow_dispatch:
    inputs:
      wing-head:
        type: string
        required: true
        default: HEAD
      wing-sync-message:
        type: string
        required: true
        default: 'chore: upgrade dae-wing'

jobs:
  sync-wing:
    runs-on: ubuntu-latest
    if: ${{ input.wing-head }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: sync wing
        run: |
          git checkout ${{ input.wing-head }}
        working-directory: wing

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ input.wing-sync-message }}
          create_branch: true
          branch: sync-wing
