#      _                _
#   __| | __ _  ___  __| |
#  / _` |/ _` |/ _ \/ _` |
# | (_| | (_| |  __/ (_| |
#  \__,_|\__,_|\___|\__,_|
#
# Copyright (C) 2023 @daeuniverse <https://github.com/daeuniverse>
#
# This is a open-source software, liscensed under the MIT License.
# See /License for more information.

name: Test check runs

on:
  workflow_dispatch:

jobs:
  instantiate-check-runs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id: ["dae-bot[bot]/checkout-full-src", "dae-bot[bot]/build-web", "dae-bot[bot]/build-bundle"]
    steps:
      - name: Instantiate required check runs
        uses: daeuniverse/ci-seed-jobs/core/daed/instantiate-check-runs@master
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          id: matrix.id
          
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id: ["dae-bot[bot]/checkout-full-src", "dae-bot[bot]/build-web", "dae-bot[bot]/build-bundle"]
    steps:
      - uses: actions/checkout@master
        id: checkout

      - name: Report result
        uses: daeuniverse/ci-seed-jobs/core/daed/report-check-run@master
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          id: matrix.id
