#      _                _
#   __| | __ _  ___  __| |
#  / _` |/ _` |/ _ \/ _` |
# | (_| | (_| |  __/ (_| |
#  \__,_|\__,_|\___|\__,_|
#
# Copyright (C) 2023 @daeuniverse <https://github.com/daeuniverse>
#
# This is a open-source software, liscensed under the MIT License.
# See /License for more information.

name: Test check runs

on:
  workflow_dispatch:

jobs:
  instantiate-check-runs:
    needs: [clone-seed-jobs]
    runs-on: ubuntu-latest
    steps:
      - uses: daeuniverse/ci-seed-jobs/core/daed/instantiate-check-runs@master
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
